del bin\*.obj
del bin\MozillaParser.dll
del bin\*.pdb
del bin\*.res

rem PLEASE RUN vsvars32.bat BEFORE YOU RUN THIS SCRIPT

SET PATH=C:\Program Files\Microsoft Visual Studio .NET\Common7\IDE;C:\Program Files\Microsoft Visual Studio .NET\VC7\BIN;C:\Program Files\Microsoft Visual Studio .NET\Common7\Tools;C:\Program Files\Microsoft Visual Studio .NET\Common7\Tools\bin\prerelease;C:\Program Files\Microsoft Visual Studio .NET\Common7\Tools\bin;C:\Program Files\Microsoft Visual Studio .NET\FrameworkSDK\bin;C:\WINDOWS\Microsoft.NET\Framework\v1.0.3705;C:\Perl\bin\;c:\;c:\WINDOWs;C:\WINDOWS\system32;C:\WINDOWS\system;C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\bin;C:\Program Files\Microsoft Visual Studio .NET 2003\Common7\IDE;C:\j2sdk1.4.2_05;C:\j2sdk1.4.2_05\jre\bin;C:\Program Files\MySQL\MySQL Server 4.1\bin;C:\cygwin\bin;C:\Program Files\Battery miser;C:\Program Files\QuickTime\QTSystem\;
rem vcvars32.bat

SET MOZILLA_SRC_HOME=c:\dapper\mozilla
SET JDK_HOME="C:\Program Files\Java\jdk1.5.0_10"

echo  Building JavaContentSink Object...
cl -Fobin\JavaContentSink.obj -c  -DMOZILLA_INTERNAL_API -DOSTYPE=\"WINNT5.1\" -DOSARCH=\"WINNT\" -DBUILD_ID=0000000000 -I%MOZILLA_SRC_HOME%/parser/htmlparser/public -I%JDK_HOME%/include -I%JDK_HOME%/include/win32 -I%MOZILLA_SRC_HOME%/dist/include/xpcom -I%MOZILLA_SRC_HOME%/dist/include/string  -I%MOZILLA_SRC_HOME%/dist/include/necko -I%MOZILLA_SRC_HOME%/dist/include/content -I%MOZILLA_SRC_HOME%/dist/include -I%MOZILLA_SRC_HOME%/dist/include -I%MOZILLA_SRC_HOME%/dist/include/nspr          -TP -nologo -W3 -Gy -Fdbin\MozillaParser.pdb  -DDEBUG -D_DEBUG -DDEBUG_felix -DTRACING -Zi -O1 -MDd           -DX_DISPLAY_MISSING=1 -DMOZILLA_VERSION=\"1.8.1\" -DMOZILLA_VERSION_U=1.8.1 -DHAVE_SNPRINTF=1 -D_WINDOWS=1 -D_WIN32=1 -DWIN32=1 -DXP_WIN=1 -DXP_WIN32=1 -DHW_THREADS=1 -DWINVER=0x400 -D_WIN32_WINNT=0x400 -DSTDC_HEADERS=1 -DWIN32_LEAN_AND_MEAN=1 -DNO_X11=1 -D_X86_=1 -DD_INO=d_ino -DMOZ_DEFAULT_TOOLKIT=\"windows\" -DMOZ_PHOENIX=1 -DMOZ_BUILD_APP=browser -DMOZ_XUL_APP=1 -DMOZ_ENABLE_CANVAS=1 -DMOZ_DISTRIBUTION_ID=\"org.mozilla\" -DOJI=1 -DIBMBIDI=1 -DMOZ_VIEW_SOURCE=1 -DACCESSIBILITY=1 -DMOZ_XPINSTALL=1 -DMOZ_JSLOADER=1 -DNS_PRINTING=1 -DNS_PRINT_PREVIEW=1 -DMOZ_XTF=1 -DMOZ_MATHML=1 -DMOZ_UPDATE_CHANNEL=default -DMOZ_FEEDS=1 -DMOZ_STORAGE=1 -DMOZ_SAFE_BROWSING=1 -DMOZ_URL_CLASSIFIER=1 -DMOZ_LOGGING=1 -DMOZ_USER_DIR=\"Mozilla\" -DHAVE_UINT64_T=1 -DMOZ_XUL=1 -DMOZ_PROFILELOCKING=1 -DMOZ_MORK=1 -DMOZ_DLL_SUFFIX=\".dll\" -DJS_THREADSAFE=1 -DMOZILLA_1_8_BRANCH=1 -DMOZILLA_LOCALE_VERSION=\"1.8.1rc\" -DMOZILLA_REGION_VERSION=\"1.8.1rc\" -DMOZILLA_SKIN_VERSION=\"1.8\"  -D_MOZILLA_CONFIG_H_ -DMOZILLA_CLIENT src\JavaContentSink.cpp

echo Building MozillaParser Object ... 
cl -Fobin\MozillaParser.obj -c  -DMOZILLA_INTERNAL_API -DOSTYPE=\"WINNT5.1\" -DOSARCH=\"WINNT\" -DBUILD_ID=0000000000   -I%MOZILLA_SRC_HOME%/parser/htmlparser/public -I%JDK_HOME%/include -I%JDK_HOME%/include/win32 -I%MOZILLA_SRC_HOME%/parser/htmlparser/src -I%MOZILLA_SRC_HOME%/intl/unicharutil/util -I%MOZILLA_SRC_HOME%/dist/include/uconv  -I%MOZILLA_SRC_HOME%/dist/include/util -I%MOZILLA_SRC_HOME%/dist/include/xpcom -I%MOZILLA_SRC_HOME%/dist/include/string  -I%MOZILLA_SRC_HOME%/dist/include/necko -I%MOZILLA_SRC_HOME%/dist/include/content -I%MOZILLA_SRC_HOME%/dist/include  -I%MOZILLA_SRC_HOME%/dist/include/nspr          -TP -nologo -W3 -Gy -Fdbin\MozillaParser.pdb  -DDEBUG -D_DEBUG -DDEBUG_felix -DTRACING -Zi -O1 -MDd           -DX_DISPLAY_MISSING=1 -DMOZILLA_VERSION=\"1.8.1\" -DMOZILLA_VERSION_U=1.8.1 -DHAVE_SNPRINTF=1 -D_WINDOWS=1 -D_WIN32=1 -DWIN32=1 -DXP_WIN=1 -DXP_WIN32=1 -DHW_THREADS=1 -DWINVER=0x400 -D_WIN32_WINNT=0x400 -DSTDC_HEADERS=1 -DWIN32_LEAN_AND_MEAN=1 -DNO_X11=1 -D_X86_=1 -DD_INO=d_ino -DMOZ_DEFAULT_TOOLKIT=\"windows\" -DMOZ_PHOENIX=1 -DMOZ_BUILD_APP=browser -DMOZ_XUL_APP=1 -DMOZ_ENABLE_CANVAS=1 -DMOZ_DISTRIBUTION_ID=\"org.mozilla\" -DOJI=1 -DIBMBIDI=1 -DMOZ_VIEW_SOURCE=1 -DACCESSIBILITY=1 -DMOZ_XPINSTALL=1 -DMOZ_JSLOADER=1 -DNS_PRINTING=1 -DNS_PRINT_PREVIEW=1 -DMOZ_XTF=1 -DMOZ_MATHML=1 -DMOZ_UPDATE_CHANNEL=default -DMOZ_FEEDS=1 -DMOZ_STORAGE=1 -DMOZ_SAFE_BROWSING=1 -DMOZ_URL_CLASSIFIER=1 -DMOZ_LOGGING=1 -DMOZ_USER_DIR=\"Mozilla\" -DHAVE_UINT64_T=1 -DMOZ_XUL=1 -DMOZ_PROFILELOCKING=1 -DMOZ_MORK=1 -DMOZ_DLL_SUFFIX=\".dll\" -DJS_THREADSAFE=1 -DMOZILLA_1_8_BRANCH=1 -DMOZILLA_LOCALE_VERSION=\"1.8.1rc\" -DMOZILLA_REGION_VERSION=\"1.8.1rc\" -DMOZILLA_SKIN_VERSION=\"1.8\"  -D_MOZILLA_CONFIG_H_ -DMOZILLA_CLIENT src\MozillaParser.cpp

rc.exe  -r -DMOZILLA_INTERNAL_API -DOSTYPE=\"WINNT5.1\" -DOSARCH=\"WINNT\" -DBUILD_ID=0000000000 -I%MOZILLA_SRC_HOME%/include -I%MOZILLA_SRC_HOME%/include/win32 -I%MOZILLA_SRC_HOME%/parser/htmlparser/public -I%MOZILLA_SRC_HOME%/dist/include/xpcom -I%MOZILLA_SRC_HOME%/dist/include/string  -I%MOZILLA_SRC_HOME%/dist/include/necko -I%MOZILLA_SRC_HOME%/dist/include/content -I%MOZILLA_SRC_HOME%/dist/include  -I%MOZILLA_SRC_HOME%/dist/include/nspr -Fobin\module.res src\module.rc

link -dll -NOLOGO -OUT:bin\MozillaParser.dll -PDB:bin\MozillaParser.pdb    -DEBUG -DEBUGTYPE:CV     bin\JavaContentSink.obj bin\MozillaParser.obj bin/module.res %MOZILLA_SRC_HOME%/dist/lib/xpcom.lib %MOZILLA_SRC_HOME%/dist/lib/xpcom_core.lib %MOZILLA_SRC_HOME%/dist/lib/nspr4.lib %MOZILLA_SRC_HOME%/dist/lib/plc4.lib %MOZILLA_SRC_HOME%/dist/lib/plds4.lib    kernel32.lib user32.lib gdi32.lib winmm.lib wsock32.lib advapi32.lib
