/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MozillaParser */

#ifndef _Included_EnviromentController
#define _Included_EnviromentController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnviromentController
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void Java_com_dappit_Dapper_parser_EnviromentController_setenv
  (JNIEnv *env , jclass, jstring variableName , jstring value );
  
  /*
 * Class:     EnviromentController
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jstring Java_com_dappit_Dapper_parser_EnviromentController_getenv
  (JNIEnv *env , jclass, jstring variableName  );

#ifdef __cplusplus
}
#endif
#endif
